[package]
name = "hp-mouse-configurator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.hidapi]
version = "1.3.4"
default-features = false
features = ["linux-static-hidraw"]
