[package]
name = "hp-mouse-configurator"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk4 = "0.4"
nix = "0.24"
relm4 = { version =  "0.4", features = ["macros"] }
udev = "0.6"

[dependencies.bitvec]
version = "1"
default-features = false
features = ["std"]
